$(document).ready(function(){
    $("#main").mouseover(function(){
        $("#maxmillan").show();
    })
})
$(document).ready(function(){
    $("#main").mouseout(function(){
        $("#maxmillan").hide();
    })
})